name: Build Simple Java App with Maven

on:
  push: 
    branches: [ "master" ]
    
jobs:
    build:
      name: Build a Java application with Maven
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          node-version: [8.x, 10.x, 12.x]
          os: [ubuntu-18.04]
          
      steps:
        - name: Checking out the code
          uses: actions/checkout@v4
        
        - name: Setup JDK 17 for x6
          uses: actions/setup-java@v3
          with: 
            distribution: 'corretto'
            java-version: '17' 
            cache : maven

        - name: Unit Tests
          run: mvn -B test --file pom.xml

        - name: Build with Maven
          run: mvn -B package --file pom.xml

        - name: Print if Build is a success
          run: echo "Build succeded"
