name: First Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
   
